### ISSUE TITLE
navbar is not present on all pages

### ISSUE THREAD

**Issue by 14Muhammad** [zaryabriaz/lhrgaadi#1]
![screenshot_1](https://user-images.githubusercontent.com/14924671/48966888-75156900-effa-11e8-98e6-d0fef8c01756.jpg)

**Comment by HammadMubeen** [comment]
Was buzy in doing assigment of Os  ......will consider this matter as soon
as possible ....INSHALLAH.

**Comment by HammadMubeen** [comment]
![image](https://user-images.githubusercontent.com/44495028/49105543-aa59cb00-f235-11e8-94cc-0886bb3aae62.png)

My nav bar resolved.

**Comment by zaryabriazucp** [comment]
we have done with this work on all pages

**Comment by AreejHasan0076** [comment]
Issue resolved.
