### ISSUE TITLE
css files merge

### ISSUE THREAD

**Issue by zaryabriazucp** [zaryabriaz/lhrgaadi#2]
merge your css files in my stylesheet.css as soon as possible

**Comment by HammadMubeen** [comment]
![image](https://user-images.githubusercontent.com/44495028/49092199-555a8c80-f216-11e8-9589-dd027ce35094.png)

**Comment by HammadMubeen** [comment]
![image](https://user-images.githubusercontent.com/44495028/49092378-c26e2200-f216-11e8-987e-d159c3a2e6cd.png)

**Comment by HammadMubeen** [comment]
![image](https://user-images.githubusercontent.com/44495028/49092430-de71c380-f216-11e8-964c-304cf058e4e7.png)
